[2024-04-22T10:17:24.017+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T10:17:24.039+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_table manual__2024-04-22T10:17:21.174510+00:00 [queued]>
[2024-04-22T10:17:24.045+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_table manual__2024-04-22T10:17:21.174510+00:00 [queued]>
[2024-04-22T10:17:24.045+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-22T10:17:24.062+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): create_table> on 2024-04-22 10:17:21.174510+00:00
[2024-04-22T10:17:24.077+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=23271) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T10:17:24.078+0000] {standard_task_runner.py:63} INFO - Started process 23278 to run task
[2024-04-22T10:17:24.079+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_table', 'manual__2024-04-22T10:17:21.174510+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp_w0u41ri']
[2024-04-22T10:17:24.081+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask create_table
[2024-04-22T10:17:24.120+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_table manual__2024-04-22T10:17:21.174510+00:00 [running]> on host b6fcd665afc9
[2024-04-22T10:17:24.190+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T10:17:21.174510+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-22T10:17:21.174510+00:00'
[2024-04-22T10:17:24.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T10:17:24.198+0000] {base.py:84} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2024-04-22T10:17:24.203+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-22T10:17:24.203+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T10:17:24.210+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_table, execution_date=20240422T101721, start_date=20240422T101724, end_date=20240422T101724
[2024-04-22T10:17:24.253+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-22T10:17:24.267+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-22T10:17:24.274+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
